WITH MAX_FISH AS (
    SELECT ID,FISH_TYPE,LENGTH
    FROM FISH_INFO
    WHERE (FISH_TYPE,LENGTH) IN (
        SELECT FISH_TYPE,MAX(LENGTH) FROM FISH_INFO 
        GROUP BY FISH_TYPE
    )
)

SELECT ID,FISH_NAME,LENGTH FROM MAX_FISH MF
JOIN FISH_NAME_INFO FNI
ON MF.FISH_TYPE=FNI.FISH_TYPE